name: rss

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  gke-release:
    runs-on: ubuntu-latest
    steps:
      - uses: guilhem/rss-issues-action@0.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          feed: "https://cloud.google.com/feeds/kubernetes-engine-release-notes.xml"
          prefix: "[GKE]"
          characterLimit: "255"
          dry-run: "false"
          lastTime: "92h"
          labels: "liens/Kubernetes"
